version: '3.7'

services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ../:/var/www/html/
    container_name: workspace
    tty: true
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    networks:
      - app-network


networks:
  app-network:
    driver: "bridge"
